name: Workflow from CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  general:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Docker
        uses: actions/docker@v4

      - name: Docker Build
        uses: |
          export IMAGE=workflow:${{ vars.VERSION_TAG }}
          echo "Image: $IMAGE"

      - name: Running
        run: |
          echo "Running from CLI"
          dotnet --version
          echo "CLI Variable: ${{ vars.BOOTS }}"
